apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nfs-server
  name: nfs-server
spec:
  ports:
    - name: "111"
      port: 111
      protocol: UDP
      targetPort: 111
    - name: "2049"
      port: 2049
      targetPort: 2049
  selector:
    io.kompose.service: nfs-server
status:
  loadBalancer: {}
